<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Testing" Version="2026.9.14.10652" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Krosoft.Extensions.Resilience\Krosoft.Extensions.Resilience.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>